update documentation
snabble/docs pull request #46
Opened 2018-11-27 09:01 UTC by anni-k

2018-11-28 09:55 UTC, g-w requested changes
* Bei "Set Payment State Request" fehlt "processing"
* Das Pricing sollte beschrieben werden
* Die Error Cases sollten beschrieben werden

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +The properties `weight`, `units` and `price` are only considered if the referenced products is of a specific type.
Der Satz is redundant zur Dokumentation in L47.

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +A shopping cart within a request from a client. Items may contain the following information:
Hier sollte noch die Struktur des `Cart` Objekts beschrieben werden.

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +| `totalPrice`      | `int`    |         | totalPrice of the product, e.g. amount * price or weight * price                                           |
Besser "Total price of the Line Item". Die Berechnung stimmt so nicht ganz und ich würde diese entfernen.

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +| `weight`          | `int`    | 0       | Weight of product in case of a weighable (not packaged) product                                            |
Besser sowas wie "Weight purchased"

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +| `weightUnit`      | `string` |         | Unit for weighable item to calculate price                                                                 |
Besser Unit of the weight.

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +| `referenceUnit`   | `string` |         | Reference unit for weighable item, e.g. if weightUnit is g referenceUnit is kg                             |
Das ist so schwer zu verstehen. Evtl. sollten wir hier einfach auf https://github.com/snabble/docs/blob/master/api_products.md#weighable-products verweisen.

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +    "paymentInformation": { .. some information depending on payment method .. }
Das hängt letztlich vom Payment System ab. Theoretisch kann eine Payment Methode viele konkrete Implementierungen haben.

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +| paymentResult      | object       | nil     | [Information from payment gateway](#payment-result), i.e. transaction id, state                    |
Besser Payment System.

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +In case of online payment the gateway will response with additional information like `transfer id`, `transfer date`, `response messages`, `state` etc.
Entweder den Sinn und Zweck besser erklären oder den Absatz streichen. So wiederholt er nur die Aussage von oben.

2018-11-28 09:55 UTC, g-w commented on api_checkout.md
> +Initiate a Checkout Process and starts payment process if all requirements are fulfilled.
Das ist verwirrend.

2018-11-28 13:12 UTC, anni-k commented
Ich habe die Informationen entsprechend ergänzt.

2018-11-28 15:41 UTC, g-w requested changes

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +The api has a structured errors object for possible cart item and shop errors. The structured error object looks like this:
Das sollten wir in das api_general.md verschieben und hier nur die Checkout spezifischen Codes beschreiben.

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| Property              | Description                              |
Hier sollten die Datentypen auch dokumentiert werden.

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| Type              | Description                                                                                                     | Message                    |
Die Message brauchen wir nicht dokumentieren. Dann können wir sie einfach ändern.

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| `shop_not_found`    | if shop does not exists                                                                                         | shop with id 'x' not found |
Hier muss der Verweis auf die `shopID` hin und evtl. ein Link auf `api_shops.md`.

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +   "message": "hop with id 'some-shop' not found"
Da fehlt ein S.
```suggestion
   "message": "Shop with id 'some-shop' not found"
```

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| Property                | Description                              |
Der Typ sollte dokumentiert werden.

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| `sku`                   | product sku                              |
```suggestion
| `sku`                   | SKU of the affected product                               |
```

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +A lineItemError Object looks like this:
```suggestion
A `LineItemError` gives further information on line item which caused an error.
```

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| `sale_stop`         | if `saleStop` flag for given product is true   | product is excluded from sale |
```suggestion
| `sale_stop`         | The product is affected by a sale stop |
```

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| `product_not_found` | product does not exists for project            | product not found             |
```suggestion
| `product_not_found` | A product with the given SKU does not exist |
```

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| `tax`              | map[string]int | Mapping of tax rates on the portion of the price                                              |
Das sollte analog zu https://github.com/snabble/docs/blob/master/api_pos_integration.md#checkout-process Dokumentiert werden.

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +##### Error Types
Wir sollten die Dokumentation zu den Requests verschieben, bei denen diese auftreten können.

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| `items`       | `array`  | Array of scanned items                                               |
```suggestion
| `items`       | `CatItem[]`  | Array of cart items                                               |
```

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| `shopID`      | `string` | ID of the shop where the client is in                                |
```suggestion
| `shopID`      | `string` | ID of the shop                                |
```

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| details               | further details                          |
```suggestion
| `details` | `Error[]` | Error details |```

2018-11-28 15:41 UTC, g-w commented on api_checkout.md
> +| `bad_shop_id`       | if shop id is not present                                                                                       | invalid shop id 'x'        |
```suggestion
| `bad_shop_id`       | The provided `shopID` is either not present or invalid                                                                                     | invalid shop id 'x'        |
```

2018-11-30 15:46 UTC, g-w commented on api_checkout.md
> +A shopping cart within a request from a client may look like this:
```suggestion
```

2018-11-30 15:48 UTC, g-w requested changes

2018-11-30 15:48 UTC, g-w commented on api_checkout.md
> +A shopping cart within a request from a client may look like this:
```suggestion
```

2018-11-30 15:48 UTC, g-w commented on api_checkout.md
> +A cart item may contain the following information:
```suggestion
A cart item may contains following properties:
```

2018-11-30 15:52 UTC, g-w approved these changes

2018-11-30 15:52 UTC, merged