Products v2
snabble/docs pull request #57
Opened 2019-01-28 11:45 UTC by g-w

2019-01-28 12:50 UTC, anni-k requested changes

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +* [Find product by weigh item id](#find-product-by-weigh-item-id): `GET /{project}/products/weighItemId/{code}` (**Deprecated**)
Ich frag mich grad, ob `GET /{project}/products/sku/{sku}` nicht ebenfalls deprecated ist. Auch hier wäre es ja schöner den neuen resolvedProducts Endpunkt zu nutzen.

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +identified by a code (ie. a EAN-13) that is printed on the
`an EAN`

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +Code templates are a way to extract information embeded into a scanned
Eher `out of` oder? Wir extrahieren ja Daten aus dem Code und packen sie nicht rein.

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +the standard. With this and the additional inforations contained in
Fehlendes `m` und `information` hat keinen Plural.

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +For example: Given the scanned code `2123455005005`. Using the
`By using`

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +yield, that this code belongs to the product `Banana` wich has a price
A product lookup might yield, that this code belongs to the product `Banana` which has a price

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +| `edeka_discount`     | Price reduction for arbitrary products                           |
Sollte der `edeka_discount` wirklich in die öffentliche Doku?

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +to shopping cart if a user buys the products. These products can not
`an`

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +bundle if scans a single product.
`by scanning a single product`

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +A product has two differen representations. The [first `Product Object
different

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +The service use content negoation to distinguish between the
`uses`

2019-01-28 12:50 UTC, anni-k commented on api_products.md
> +**Deprecated**
Sollten wir nich auch die neuen Endpunkte beschreiben? (resolvedProducts/...)

2019-01-28 13:02 UTC, J-Rocke commented on api_products.md
> +* [Find product by weigh item id](#find-product-by-weigh-item-id): `GET /{project}/products/weighItemId/{code}` (**Deprecated**)
Solange es `PUT /{project}/products/sku/{sku}` gibt sollte dort auch ein GET möglich sein würde ich sagen

2019-01-28 13:16 UTC, g-w commented on api_products.md
> +* [Find product by weigh item id](#find-product-by-weigh-item-id): `GET /{project}/products/weighItemId/{code}` (**Deprecated**)
`resolvedProducts` ist keine öffentliche API. Daher ist das keine Alternative.

2019-01-28 13:18 UTC, g-w commented on api_products.md
> +**Deprecated**
Nein. Die sind im Moment nur für die Apps.

2019-01-28 13:41 UTC, J-Rocke requested changes

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +upfornt. These products are modeled as weighable products (which also
TYPO upfront

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +include products that are sold by other meassures). Finally, there are
TYPO measures - ohne Doppel-S

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +deposit products and products that bundle other products, ie. a box of
crate statt box ?

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +| ml           | Mililiter                                                                                                      |
TYPO Milliliter - Doppel-L

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +be bought without buying the product.
Alternative, klare Formulierung:
"Deposit products can not be bought on their own."

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +Bundles are products that contain other products, ie. a box of beer
crate

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +The service use content negoation to distinguish between the
negotiation

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +representation. Please use
representations Mehrzahl

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +| `taxCategory`       | `string`   | null      |                                                                                                           |
Beschreibung fehlt. Relativ klar aber die anderen offensichtlichen haben auch eine

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +| `depositProduct`    | `string`   | null      | The SKU of a corresponding product containing the associated deposit article                              |
The SKU of the associated deposit article
Ein Produkt enthält ja keine article sondern repräsentiert sie

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +| `taxCategory`       | `string`   | null      |                                                                                                           |
Das Feld ist schon weiter oben beschrieben

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
Deprecation?

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +| `weighByCustomer` | `bool`     | false   | Flag, if the product is prepackaged, ot the customer has to do weighting by himself                       |
TYPO or statt ot

2019-01-28 13:41 UTC, J-Rocke commented on api_products.md
> +| `weighByCustomer`   | `bool`     | false     | Flag, if the product is prepackaged, ot the customer has to do weighting by himself                       |
TYPO or statt ot

2019-01-28 14:28 UTC, g-w commented
@anni-k @J-Rocke Ich habe die Änderungen gemacht. Könntet Ihr noch einmal darüberschauen.

2019-01-28 14:57 UTC, J-Rocke approved these changes

2019-01-28 16:06 UTC, J-Rocke requested changes

2019-01-28 16:06 UTC, J-Rocke commented on api_products.md
> +| `template`         | `string` | "default" | Identifier of the [code template](#code-templates) used                                                            |
Der Link funktioniert nicht.

2019-01-28 16:27 UTC, anni-k approved these changes

2019-01-30 13:53 UTC, J-Rocke approved these changes

2019-01-30 13:53 UTC, merged