Pos
snabble/docs pull request #61
Opened 2019-03-29 15:30 UTC by g-w

2019-03-29 15:44 UTC, anni-k requested changes

2019-03-29 15:44 UTC, anni-k commented on api_checkout.md
> +| `refersTo`        | `string` | null    | Line Item that is related to this one (ie. if the Line Item represents a deposit the id of the line item wich requires it) |
Wir sollten line item entweder durchgehen klein oder durchgehend groß schreiben. Wobei ich für klein wäre.

2019-03-29 15:44 UTC, anni-k commented on api_vpos.md
> +      "sku", "bottle",
`:` statt `,`

2019-03-29 15:44 UTC, anni-k commented on api_vpos.md
> +      "saleRestriction": "min_age_18"
`,` fehlt

2019-03-29 15:44 UTC, anni-k commented on api_vpos.md
> +| `sale_stop`         | Product can't be sold                 |
Sollten wir nicht eine Form benutzen? Entweder could oder can

2019-03-29 15:44 UTC, anni-k commented on api_vpos.md
> +used authentication scheme is `Bearer`. Additionally authorization
`authentification`

2019-03-29 15:44 UTC, anni-k commented on api_vpos.md
> +After snabble has processed the the checkout it sends an request to
`the the` und `a request`

2019-03-29 15:44 UTC, anni-k commented on api_vpos.md
> +the vPOS. This request contains all information on the checkout.
`information to`

2019-03-29 15:44 UTC, anni-k commented on api_vpos.md
> +  "state": completed"
`"completed"`

2019-03-29 15:44 UTC, anni-k commented on api_vpos.md
> +property `externalCheckoutId`. These is stored. Further it might
`These are` oder  `This is`

2019-04-01 07:58 UTC, g-w commented on api_vpos.md
> +| `sale_stop`         | Product can't be sold                 |
Das wäre falsch, oder?

2019-04-01 08:03 UTC, g-w commented on api_checkout.md
> +| `refersTo`        | `string` | null    | Line Item that is related to this one (ie. if the Line Item represents a deposit the id of the line item wich requires it) |
Habe ich angepasst.

2019-04-01 08:03 UTC, g-w commented on api_vpos.md
> +      "sku", "bottle",
Done

2019-04-01 08:03 UTC, g-w commented on api_vpos.md
> +      "saleRestriction": "min_age_18"
Done

2019-04-01 08:04 UTC, g-w commented on api_vpos.md
> +  "state": completed"
Done.

2019-04-01 08:04 UTC, g-w commented on api_vpos.md
> +property `externalCheckoutId`. These is stored. Further it might
Done

2019-04-01 08:09 UTC, anni-k approved these changes

2019-04-01 08:09 UTC, merged